### ISSUE TITLE
Empty recent list

### ISSUE THREAD

**Issue by juanfcocontreras** [grigorye/Handsfree#5]
I am testing the application and it works correctly on my Pixel 7a. However, even though I have given it all the necessary permissions, the recent calls list does not populate. In fact, if I disable showing favorite contacts (which work correctly), the calls list appears empty. How can I debug this issue?

**Comment by grigorye** [comment]
Hi there, thanks for the report! Do you build from source? App versions (both Garmin watch app and Android companion) are the first thing that is necessary to figure out... Also it would be *very helpful* to know your *watch* model in this case. If it's just "Recents" that does not work, it may be due to memory limitations of the particular model: that is something that I have been actively tackling this/last year, so I'm really interested to figure it out.

If you want to debug it, you should have logs on both apps and etc. Those can be obtained via `adb` (for Android) and by grabbing the log from GARMIN/APPS/LOGS from the watch. I'll try to publish a guide on how to do that shortly.

**Comment by juanfcocontreras** [comment]
Hello, I haven't compiled them from source, I installed both from the app stores. My watch is a Garmin Forerunner 255 Music, do you think it's possible that it is the problem?

**Comment by grigorye** [comment]
> My watch is a Garmin Forerunner 255 Music

It's a very capable watch. So *this* should not be a problem. OTOH, v1 of the watch app (currently available in Garmin Connect IQ) does not have Recents functionality, nor most of the other new features. That functionality will be available in v2 (will be released soon). I feel like (non-beta) version of Android app already mentions Recents and that's misleading, correct?

**Comment by juanfcocontreras** [comment]
Yes, it indeed appears as an option and that's why it has confused me.

I will look forward to version v2 with interest!

**Comment by grigorye** [comment]
> Yes, it indeed appears as an option and that's why it has confused me.
> 
> I will look forward to version v2 with interest!

Understood. Sorry for the confusion, and thanks again for the report! I was not realizing that the non-stable version already mentions that (I released it quite long time ago, and followed with betas-only afterwards). I'm afraid to add "beta" tags in UI there (as I believe it could be rejected by Google then). OTOH, I would like that most of the users already run the (Android app) version that is capable of supporting the features of v2 of the watch app, by the time it is released, to avoid the upgrade/compatibility hassle. And hiding those v2-only elements from UI, when running Android app against v1 of watch app is technically a challenge (and can again raise questions with the Google review team). Hence, I ended up making these kinds of compromises.

**Comment by grigorye** [comment]
Just in case, you can check `[beta]` tags in the feature list, for stuff that is scheduled for v2.

**Comment by juanfcocontreras** [comment]
> Just in case, you can check `[beta]` tags in the [feature list](https://github.com/grigorye/Handsfree?tab=readme-ov-file#features), for the stuff that is scheduled for v2.

ah, thank you very much!

**Comment by grigorye** [comment]
>  I installed both from the app stores

I've just realized that I was wrong and there should be *no* non-beta version published on Google Play. From that perspective, I wonder if you could share the exact version number that you have for the Android companion app? (It should be shown on About tab). Thanks!

**Comment by juanfcocontreras** [comment]
Hello, well just yesterday it updated to the version 0.0.15 (78) 47716bcd (release)

The version on the watch is the same, and I understand that it's normal for the beta options to still not appear for me, right?

**Comment by grigorye** [comment]
> Hello, well just yesterday it updated to the version 0.0.15 (78) [47716bc](https://github.com/grigorye/Handsfree/commit/47716bcd774eec4ff9a94889b13c000559b156c5) (release)

Now I understand what is happening, thanks: the thing is that this version is a beta, but open testing. So (if I get it correctly) it's available for you even you're not a beta tester (correct?). Sorry for the confusion.

> The version on the watch is the same, and I understand that it's normal for the beta options to still not appear for me, right?

Yes, it's expected.

**Comment by grigorye** [comment]
Just in case, Watch app v2 was released yesterday.

**Comment by juanfcocontreras** [comment]
Great! Thank you so much. I have seen that the version on the Google Play Store is still not updated; it will take a little while, right?

**Comment by juanfcocontreras** [comment]
> > I have seen that the version on the Google Play Store is still not updated; it will take a little while, right?
> 
> Tbh, I'm not sure about it. It shows "Updated on May 18, 2025" for me, so that should be it. (Version-wise it should be 0.0.17)

Ah, that's true. When I opened the new version of the watch, it told me that I had to update the Android version. But I uninstalled the Android version and installed the latest one from the Google Play Store, and it is indeed 0.0.17. I'll close this issue if is ok for you.

Thank you very much for everything!

**Comment by grigorye** [comment]
(Please let me know if you encounter any problem)
